DB authentication
vlykhvar/hibernate-theater pull request #10
Opened 2021-02-27 13:27 UTC by vlykhvar

Configure DB authentication instead of In memory authentication
Add Role entity, Dao and Service layer for it.
Use BCryptPasswordEncoder for storing passwords in secured way
Configure role access to specific resources for ADMIN and for USER. For example only ADMIN can add new movies or movie sessions.

2021-02-27 14:38 UTC, YuraBondarenko approved these changes

2021-02-27 14:38 UTC, YuraBondarenko commented on src/main/java/com/dev/theater/service/impl/UserServiceImpl.java
>      }
why did you remove "passwordEncoder"?

2021-03-01 08:41 UTC, KseniiaMakarova requested changes

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/confing/AppConfig.java
> +        "com.dev.theater.confing"
```suggestion
        "com.dev.theater.config"
```

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/confing/DataInitializer.java
> +package com.dev.theater.confing;
```suggestion
package com.dev.theater.config;
```

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/confing/DataInitializer.java
> +    public void addAdmin() {
let's make these 2 methods private and call them inside one `@PostConstruct` method
conceptually this is a bit confusing)

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/confing/SecurityConfig.java
> +                .antMatchers(HttpMethod.POST, "/movies").hasRole("USER")
only admin can create new movies

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/confing/SecurityConfig.java
> +                .antMatchers(HttpMethod.POST, "/movie-sessions/").hasRole("ADMIN")
are these lines different?

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/confing/SecurityConfig.java
> +
what about .httpBasic()?

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/confing/SecurityConfig.java
>      }
do you need this?

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/dao/impl/RoleDaoImpl.java
> +                    .uniqueResultOptional().orElseThrow();
can we simplify this?

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/dao/impl/RoleDaoImpl.java
> +
redundant empty line

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/model/User.java
> +    private Set<Role> roleName;
```suggestion
    private Set<Role> roles;
```

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/model/User.java
> +    @OneToMany
reconsider this relationship - see checklist

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/security/impl/AuthenticationServiceImpl.java
> +        newUser.getRoleName().add(roleService.getRoleByName("User"));
do you have `User` role?

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/dao/impl/UserDaoImpl.java
>      public Optional<User> findByEmail(String email) {
what about findById() method? let's use join fetch there as well

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/security/UserDetailsServiceImp.java
> +public class UserDetailsServiceImp implements UserDetailsService {
```suggestion
public class UserDetailsServiceImpl implements UserDetailsService {
```

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/security/UserDetailsServiceImp.java
> +    private UserService userService;
```suggestion
    private final UserService userService;
```

2021-03-01 08:41 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/security/UserDetailsServiceImp.java
> +    }
do you need this?

2021-03-01 11:51 UTC, KseniiaMakarova approved these changes
good job!

2021-03-01 12:51 UTC, merged