last changes
vlykhvar/hibernate-theater pull request #11
Opened 2021-03-01 14:43 UTC by vlykhvar

2021-03-01 15:22 UTC, gigbat approved these changes

2021-03-01 16:16 UTC, KseniiaMakarova requested changes
remove all redundant branches from GitHub please

in your IDE - open global search in the project directory and search `movie` or `cinema`
all the occurrences should be replaced

2021-03-01 16:16 UTC, KseniiaMakarova commented on README.md
> +- add a ticket to his shopping card
```suggestion
- View all available games
- View all stadiums
- View game matches
- View his own order history
- Find match by date
- Make an order
- Add a ticket to his shopping cart
```

2021-03-01 16:16 UTC, KseniiaMakarova commented on README.md
> +2. Download and install the MySQL
what about Tomcat?

2021-03-01 16:16 UTC, KseniiaMakarova commented on README.md
> +5. Configure file db.properties by according to your database settings
```suggestion
5. Configure file db.properties according to your database settings.
```

2021-03-01 16:16 UTC, KseniiaMakarova commented on README.md
> +6. Run the project!
is admin injected in your app? how can I test the app with ADMIN role?

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/controller/CinemaHallController.java
> +public class CinemaHallController {
should we rename this?

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/controller/CinemaHallController.java
> +    public List<StadiumResponseDto> getAllCinemaHall() {
all the methods as well

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/controller/MovieController.java
> +public class MovieController {
same

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/controller/MovieSessionController.java
> +public class MovieSessionController {
same

also change authorization settings in SecurityConfig

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/controller/ShoppingCartController.java
>      public void addMovieSession(Authentication authentication, @RequestParam Long movieSessionId) {
rename this as well

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/service/impl/GameSessionServiceImpl.java
> +    public List<GameSession> findAvailableSessions(Long movieId, LocalDate date) {
rename this

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/service/impl/GameServiceImpl.java
> +    public Game findById(Long movieId) {
same

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/service/StadiumService.java
> +    Stadium findById(Long cinemaHallId);
same

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/service/GameSessionService.java
> +    List<GameSession> findAvailableSessions(Long movieId, LocalDate date);
same

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/service/GameService.java
> +    Game findById(Long movieId);
same

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/model/dto/GameSessionResponseDto.java
> +    }
what is going on?))

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/model/dto/GameSessionRequestDto.java
>      private Long movieId;
rename this

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/model/Ticket.java
> +    public void setMovieSession(GameSession gameSession) {
rename getters and setters

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/mapper/StadiumMapper.java
> +    public StadiumResponseDto cinemaHallToDto(Stadium stadium) {
fix method names

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/mapper/GameMapper.java
> +    public GameResponseDto movieToDto(Game game) {
same

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/dao/impl/StadiumDaoImpl.java
> +    public Stadium findById(Long cinemaHallId) {
rename this

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/dao/impl/StadiumDaoImpl.java
>              throw new CrudException("Error getting all hall", e);
same

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/dao/impl/GameSessionDaoImpl.java
> +    public Optional<GameSession> getById(Long movieSessionId) {
same

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/dao/impl/GameSessionDaoImpl.java
>              throw new CrudException("Can't update moviesession: "
same

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/dao/impl/GameSessionDaoImpl.java
> +    public List<GameSession> findAvailableSessions(Long movieId, LocalDate date) {
same

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/dao/impl/GameDaoImpl.java
>              throw new CrudException("Error getting all movies", e);
same for all exception messages

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/dao/StadiumDao.java
> +    Stadium findById(Long cinemaHallId);
same

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/dao/GameSessionDao.java
> +    List<GameSession> findAvailableSessions(Long movieId, LocalDate date);
same

2021-03-01 16:16 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/dao/GameDao.java
> +    Game findById(Long movieId);
same

2021-03-01 17:20 UTC, vlykhvar commented on src/main/java/com/dev/football/model/dto/GameSessionRequestDto.java
>      private Long movieId;
strange. it was renamed

2021-03-01 17:22 UTC, vlykhvar commented on src/main/java/com/dev/football/mapper/StadiumMapper.java
> +    public StadiumResponseDto cinemaHallToDto(Stadium stadium) {
strange2. it was renamed

2021-03-01 17:22 UTC, vlykhvar commented on src/main/java/com/dev/football/mapper/GameMapper.java
> +    public GameResponseDto movieToDto(Game game) {
strange3. it was renamed

2021-03-01 17:23 UTC, vlykhvar commented on src/main/java/com/dev/football/dao/impl/StadiumDaoImpl.java
> +    public Stadium findById(Long cinemaHallId) {
strange3. it was renamed

2021-03-02 07:36 UTC, KseniiaMakarova approved these changes

2021-03-02 07:36 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/model/dto/GameSessionResponseDto.java
> +    public void setGameSessionDescription(String stadiumDescription) {
```suggestion
    public String getStadiumDescription() {
        return stadiumDescription;
    }

    public void setStadiumDescription(String stadiumDescription) {
```

2021-03-02 07:36 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/mapper/GameSessionMapper.java
> +        gameSessionDto.setGameSessionDescription(gameSession.getStadium().getDescription());
```suggestion
        gameSessionDto.setStadiumDescription(gameSession.getStadium().getDescription());
```

2021-03-02 07:36 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/dao/impl/StadiumDaoImpl.java
> +            throw new CrudException("Error getting all hall", e);
```suggestion
            throw new CrudException("Error getting all stadiums", e);
```

2021-03-02 07:36 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/dao/impl/GameDaoImpl.java
> +            throw new CrudException("Error getting all movies", e);
```suggestion
            throw new CrudException("Error getting all games", e);
```

2021-03-02 07:36 UTC, KseniiaMakarova commented on src/main/java/com/dev/football/dao/impl/GameDaoImpl.java
> +            throw new CrudException("Can't get movie on id " + gameId);
```suggestion
            throw new CrudException("Can't get game on id " + gameId);
```

2021-03-02 07:54 UTC, merged