all done
vlykhvar/hibernate-theater pull request #7
Opened 2021-02-16 14:09 UTC by vlykhvar

> CinemaHallController

1. Add cinema hall - POST: /cinema-halls
2. Get all cinema halls - GET: /cinema-halls

> MovieController

1. Add a movie - POST: /movies
2. Get all movies - GET: /movies

> MovieSessionController

1. Add movie session - POST: /movie-sessions
2. Get all available movie sessions - GET: /movie-sessions/available?movieId=1&date=29.02.2020
3. Update movie session - PUT /movie-sessions
4. Remove movie session - DELETE /movie-sessions

2021-02-16 14:14 UTC, Ketch92 approved these changes

2021-02-16 14:49 UTC, KseniiaMakarova requested changes

2021-02-16 14:49 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/controller/CinemaHallController.java
> +    public void addCinemaHall(CinemaHallResponseDto cinemaHallDto) {
why responseDto here?

2021-02-16 14:49 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/controller/MovieController.java
> +@RequestMapping("/movie")
```suggestion
@RequestMapping("/movies")
```

2021-02-16 14:49 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/controller/MovieController.java
> +    public void addMovie(@RequestBody MovieRequestDto movieRequestDtoDto) {
```suggestion
    public void addMovie(@RequestBody MovieRequestDto movieRequestDto) {
```

2021-02-16 14:49 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/controller/MovieSessionController.java
> +@RequestMapping("/moviesessions")
see task description - what the mapping should be?

2021-02-16 14:49 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/controller/MovieSessionController.java
> +    public void addMovieSession(@RequestBody MovieSessionRequestDto movieSessionResponseDto) {
```suggestion
    public void addMovieSession(@RequestBody MovieSessionRequestDto movieSessionRequestDto) {
```

2021-02-16 14:49 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/mapper/CinemaHallMapper.java
> +    public CinemaHall dtoToCinemaHall(CinemaHallResponseDto cinemaHallDto) {
why responseDto?

2021-02-16 14:49 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/mapper/MovieSessionMapper.java
> +        movieSession.setCinemaHall(new CinemaHall());
we should get movieId and cinemaHallId in the movieSessionRequestDto

then we should fetch entities by their ids through `movieService` and `cinemaHallService`
and set them to the movieSession

2021-02-16 14:49 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/model/dto/MovieSessionRequestDto.java
> +    private String cinemaHallDescription;
the only informative fields that we can get from this dto are:
`movieId`
`cinemaHallId`
`showTime`

let's refactor the fields

2021-02-17 05:53 UTC, KseniiaMakarova approved these changes

2021-02-17 05:53 UTC, KseniiaMakarova commented on src/main/java/com/dev/theater/controller/CinemaHallController.java
> +    public void addCinemaHall(CinemaHallRequestDto cinemaHallRequestDto) {
let's test this method and see what may be missing  comparing to POST method in other controllers

2021-02-17 06:36 UTC, merged